@extends('layouts.tabler')
@section('title', 'Dashboard — PanduPOS')
@section('header', 'Dashboard · '.Str::headline($role))
@section('content')
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2 mb-3"><div><div class="text-secondary">Ringkasan real-time untuk</div><h2 class="m-0">{{ $tenant->name ?? 'Tenant' }}</h2></div><span class="badge bg-green-lt">Auto-refresh 60 detik</span></div>
@if($canViewFinancial)<div class="row row-cards mb-3">
    <div class="col-sm-6 col-xl-3"><div class="card report-stat"><div class="card-body"><div class="subheader">Omzet bulan ini</div><div class="h2">Rp {{ number_format($sales['revenue'] ?? 0,0,',','.') }}</div><div class="text-secondary">{{ $sales['invoices'] ?? 0 }} invoice final</div></div></div></div>
    <div class="col-sm-6 col-xl-3"><div class="card report-stat"><div class="card-body"><div class="subheader">Pembayaran hari ini</div><div class="h2">Rp {{ number_format($todayPayments,0,',','.') }}</div><div class="text-secondary">Terakumulasi lintas metode</div></div></div></div>
    <div class="col-sm-6 col-xl-3"><div class="card report-stat"><div class="card-body"><div class="subheader">Approval pending</div><div class="h2">{{ $pendingApprovals }}</div><a href="{{ route('approvals.index') }}" class="text-secondary">Tinjau transaksi besar</a></div></div></div>
    <div class="col-sm-6 col-xl-3"><div class="card report-stat"><div class="card-body"><div class="subheader">Paket & usage</div><div class="h2">{{ $plan->name ?? '—' }}</div><div class="text-secondary">Produk {{ $usage['products.max']['used'] ?? 0 }} / {{ $usage['products.max']['limit'] ?? '∞' }}</div></div></div></div>
</div>@endif
<div class="row row-cards mb-3">@foreach($roleMetrics as [$label,$value])<div class="col-md-4"><div class="card role-focus-card"><div class="card-body"><div class="subheader">Fokus {{ Str::headline($role) }}</div><div class="h3 mb-1">{{ $value }}</div><div class="text-secondary">{{ $label }}</div></div></div></div>@endforeach</div>
@if($canViewFinancial)
<div class="card mb-3"><div class="card-header"><h3 class="card-title">Tren pendapatan 7 hari</h3><div class="card-actions"><a href="{{ route('reports.show','bisnis') }}">Lihat laporan</a></div></div><div class="card-body"><div class="chart-shell"><canvas id="dashboard-chart"></canvas></div></div></div>
@endif
<div class="row row-cards">
    @if($canViewFinancial && in_array($role,['cashier','sales','tenant-owner','tenant-admin','manager','platform-admin']))<div class="col-lg-7"><div class="card"><div class="card-header"><h3 class="card-title">Penjualan terbaru</h3><div class="card-actions"><a class="btn btn-sm btn-primary" href="{{ route('pos.index') }}">Buka POS</a></div></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Invoice</th><th>Status</th><th>Pembayaran</th><th>Total</th></tr></thead><tbody>@forelse($recentSales as $invoice)<tr><td>{{ $invoice->invoice_no ?: '#'.$invoice->id }}</td><td>{{ $invoice->status }}</td><td>{{ $invoice->payment_status }}</td><td>Rp {{ number_format($invoice->total,0,',','.') }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">Belum ada penjualan.</td></tr>@endforelse</tbody></table></div></div></div>@endif
    @if(in_array($role,['warehouse','purchasing','tenant-owner','tenant-admin','manager','platform-admin']))<div class="col-lg-5"><div class="card"><div class="card-header"><h3 class="card-title">Produk perlu perhatian</h3></div><div class="list-group list-group-flush">@forelse($lowStock as $product)<div class="list-group-item d-flex justify-content-between"><span>{{ $product->name }}</span><span class="badge bg-yellow-lt">Min {{ $product->alert_quantity }}</span></div>@empty<div class="list-group-item text-secondary">Belum ada produk.</div>@endforelse</div></div></div>@endif
    @if($canViewFinancial && in_array($role,['purchasing','tenant-owner','tenant-admin','manager','platform-admin']))<div class="col-12"><div class="card"><div class="card-header"><h3 class="card-title">Pembelian terbaru</h3></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Referensi</th><th>Status</th><th>Total</th><th>Dibuat</th></tr></thead><tbody>@forelse($recentPurchases as $purchase)<tr><td>{{ $purchase->ref_no ?: '#'.$purchase->id }}</td><td>{{ $purchase->status }}</td><td>Rp {{ number_format($purchase->total,0,',','.') }}</td><td>{{ $purchase->created_at }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">Belum ada pembelian.</td></tr>@endforelse</tbody></table></div></div></div>@endif
</div>
@endsection
@push('scripts')
@if($canViewFinancial)<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>new Chart(document.getElementById('dashboard-chart'),{type:'line',data:{labels:@json($chart['labels']),datasets:[{data:@json($chart['values']),borderColor:'#087a54',backgroundColor:'rgba(8,122,84,.1)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true},x:{grid:{display:false}}}}});setTimeout(()=>window.location.reload(),60000);</script>@endif
@endpush
