@extends('layouts.public')
@section('title', 'PanduPOS — POS dan Inventory Multi-Cabang')
@section('description', 'Kelola kasir, stok, pembelian, penjualan, dan laporan multi-cabang tanpa spreadsheet yang tercerai-berai.')
@section('content')
<section class="hero"><div class="public-container hero-grid">
    <div class="hero-copy"><span class="eyebrow">OPERASIONAL RITEL, TANPA TEBAK-TEBAKAN</span><h1>Kasir cepat. Stok akurat. Keputusan lebih tenang.</h1><p>PanduPOS menyatukan transaksi, gudang, pembelian, pelanggan, dan kontrol SaaS dalam satu sistem modular yang siap dipakai banyak cabang.</p><div class="hero-actions"><a class="button button-primary" href="{{ route('login') }}">Coba Demo</a><a class="button button-secondary" href="{{ route('docs') }}">Lihat Dokumentasi</a></div><div class="trust-row"><span>Ledger stok immutable</span><span>API v1</span><span>Offline-ready</span><span>Multi-tenant</span></div></div>
    <div class="browser-shot hero-visual scale-in" aria-label="Dashboard PanduPOS yang berjalan"><div class="browser-bar"><i></i><i></i><i></i><small>/dashboard</small></div><img src="{{ asset('marketing/screens/dashboard.png') }}" alt="Dashboard operasional PanduPOS dengan data demo" width="1440" height="900"></div>
</div></section>
<section class="personas"><div class="public-container persona-grid"><span>Toko ritel</span><span>F&amp;B</span><span>Distributor</span><span>Multi-cabang</span><span>SaaS operator</span></div></section>
<section class="section reveal"><div class="public-container"><div class="section-heading"><span class="eyebrow">DARI FRAGMENTASI KE KONTROL</span><h2>Satu sumber data untuk seluruh operasional</h2></div><div class="problem-grid"><article class="problem-card"><span class="label label-old">Sebelumnya</span><h3>Spreadsheet dan chat terpisah</h3><p>Stok tidak sinkron, status pembelian terlambat, dan laporan baru selesai ketika keputusan sudah lewat.</p></article><article class="problem-card solution"><span class="label">Dengan PanduPOS</span><h3>Setiap transaksi langsung tercatat</h3><p>Kasir, gudang, owner, dan platform admin melihat data yang sama dengan kontrol akses yang jelas.</p></article></div></div></section>
<section id="fitur" class="section section-muted"><div class="public-container"><div class="section-heading reveal"><span class="eyebrow">FITUR INTI</span><h2>Dibangun untuk alur bisnis nyata</h2></div><div class="feature-grid">
@foreach([['Kasir POS', 'Checkout atomic, split payment, hold/resume, retur, dan struk siap cetak.'],['Inventory', 'Ledger per gudang, transfer aman, weighted average cost, serta proteksi oversell.'],['Pembelian', 'Purchase order dan penerimaan parsial yang menambah stok tepat satu kali.'],['Multi-cabang', 'Cabang, gudang, register, user, dan role berada dalam tenant yang terisolasi.'],['Laporan', 'Ringkasan penjualan, persediaan, pembelian, dan laba berbasis COGS aktual.'],['Offline sync', 'Push/pull berbasis cursor, idempotency, dan penanganan konflik perangkat.'],['SaaS billing', 'Plan, entitlement, subscription lifecycle, coupon, dan affiliate commission.'],['Audit & keamanan', 'Permission berlapis, webhook HMAC, request ID, dan audit trail.']] as $index => [$name, $copy])
<article class="feature-card card-lift reveal" style="transition-delay: {{ ($index % 4) * 70 }}ms"><span class="feature-number">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span><h3>{{ $name }}</h3><p>{{ $copy }}</p></article>
@endforeach
</div></div></section>
@php($featureStories = [
    ['screen' => 'pos.png', 'url' => '/pos', 'eyebrow' => 'TRANSAKSI', 'title' => 'Kasir yang fokus pada kecepatan dan akurasi', 'copy' => 'Operator dapat menyelesaikan checkout dengan alur ringkas, sementara validasi stok dan pembayaran tetap berjalan atomik.', 'bullets' => ['Split payment dan idempotency', 'Proteksi oversell', 'Pelanggan opsional', 'Struk transaksi', 'Retur dan void berbasis izin']],
    ['screen' => 'dashboard.png', 'url' => '/dashboard', 'eyebrow' => 'KONTROL HARIAN', 'title' => 'Dashboard berbeda untuk setiap tanggung jawab', 'copy' => 'Owner, kasir, purchasing, dan gudang memperoleh ringkasan yang relevan tanpa membuka laporan yang tidak diperlukan.', 'bullets' => ['Widget per role', 'Penjualan terbaru', 'Pembelian terbaru', 'Peringatan stok', 'Auto-refresh 60 detik']],
    ['screen' => 'report-business.png', 'url' => '/reports/bisnis', 'eyebrow' => 'LAPORAN BISNIS', 'title' => 'Tren omzet tanpa rekap manual', 'copy' => 'Filter periode dan pengelompokan harian, mingguan, atau bulanan membantu tim membaca perubahan kinerja.', 'bullets' => ['Chart interaktif', 'Summary cards', 'Tabel detail', 'Export CSV', 'Export PDF']],
    ['screen' => 'report-finance.png', 'url' => '/reports/keuangan', 'eyebrow' => 'KEUANGAN', 'title' => 'Pendapatan, COGS, dan laba dalam satu tampilan', 'copy' => 'Angka finansial diturunkan dari transaksi aktual sehingga keputusan margin tidak bergantung pada spreadsheet terpisah.', 'bullets' => ['Pendapatan', 'COGS aktual', 'Laba kotor', 'Status pembayaran', 'Rentang tanggal']],
    ['screen' => 'report-operations.png', 'url' => '/reports/operasional', 'eyebrow' => 'OPERASIONAL', 'title' => 'Pantau arus stok dan nilai persediaan', 'copy' => 'Tim gudang melihat mutasi masuk-keluar, valuasi, dan indikator yang dapat ditelusuri kembali ke ledger.', 'bullets' => ['Mutasi stok', 'Valuasi persediaan', 'Audit trail', 'Multi-gudang', 'Responsive table']],
    ['screen' => 'approvals.png', 'url' => '/approvals', 'eyebrow' => 'KONTROL RISIKO', 'title' => 'Transaksi besar menunggu persetujuan', 'copy' => 'Threshold dapat diatur per tenant. Stok dan pembayaran belum berubah sebelum transaksi benar-benar disetujui.', 'bullets' => ['Threshold dinamis', 'Approve/reject', 'Alasan penolakan', 'Audit pelaku dan waktu', 'Tanpa mutasi stok prematur']],
])
<section class="section screenshot-features"><div class="public-container"><div class="section-heading reveal"><span class="eyebrow">TAMPILAN APLIKASI NYATA</span><h2>Lihat alurnya, bukan sekadar janji fiturnya</h2><p>Seluruh gambar berikut diambil otomatis dari PanduPOS yang berjalan dengan data demo.</p></div>
@foreach($featureStories as $story)<article class="screenshot-story reveal"><div class="browser-shot"><div class="browser-bar"><i></i><i></i><i></i><small>{{ $story['url'] }}</small></div><img src="{{ asset('marketing/screens/'.$story['screen']) }}" alt="{{ $story['title'] }}" loading="lazy" width="1440" height="900"></div><div class="screenshot-copy"><span class="eyebrow">{{ $story['eyebrow'] }}</span><h2>{{ $story['title'] }}</h2><p>{{ $story['copy'] }}</p><ul>@foreach($story['bullets'] as $bullet)<li>{{ $bullet }}</li>@endforeach</ul></div></article>@endforeach
</div></section>
<section class="section section-muted"><div class="public-container"><div class="section-heading reveal"><span class="eyebrow">GALERI PRODUK</span><h2>Enam halaman penting dalam satu pandangan</h2></div><div class="screenshot-gallery">@foreach($featureStories as $story)<figure class="card-lift reveal"><img src="{{ asset('marketing/screens/'.$story['screen']) }}" alt="{{ $story['title'] }}" loading="lazy"><figcaption>{{ $story['title'] }}</figcaption></figure>@endforeach</div></div></section>
<section class="section"><div class="public-container"><div class="section-heading reveal"><span class="eyebrow">UNTUK CARA KERJA ANDA</span><h2>Satu fondasi, empat sudut pandang</h2></div><div class="usecase-grid"><article><strong>Owner</strong><p>Pantau omzet, laba, dan cabang tanpa menunggu rekap manual.</p></article><article><strong>Kasir</strong><p>Proses transaksi cepat dengan antarmuka fokus dan tahan kesalahan.</p></article><article><strong>Gudang</strong><p>Terima, pindah, dan audit stok dengan ledger yang dapat ditelusuri.</p></article><article><strong>Platform Admin</strong><p>Kelola tenant, paket, modul, billing, dan kesehatan platform.</p></article></div></div></section>
<section class="section section-muted"><div class="public-container"><div class="section-heading reveal"><span class="eyebrow">AKUN DEMO</span><h2>Uji alurnya langsung</h2></div><div class="table-wrap reveal"><table class="public-table"><thead><tr><th>Role</th><th>Email</th><th>Password</th><th>Cakupan</th></tr></thead><tbody>@foreach([['Owner','owner@demo.local','Operasional lengkap'],['Manager','manager@demo.local','Laporan dan approval'],['Kasir','cashier@demo.local','POS dan transaksi'],['Gudang','warehouse@demo.local','Stok dan mutasi'],['Purchasing','purchasing@demo.local','Pembelian'],['Sales','sales@demo.local','Penjualan'],['Pelanggan','customer@demo.local','Portal mandiri di /portal']] as [$role,$email,$scope])<tr><td>{{ $role }}</td><td><code>{{ $email }}</code></td><td><code>password</code></td><td>{{ $scope }}</td></tr>@endforeach<tr><td>Platform Admin</td><td colspan="2">Dikonfigurasi melalui environment</td><td>Kontrol SaaS lintas tenant</td></tr></tbody></table></div></div></section>
<section class="section"><div class="public-container"><div class="section-heading reveal"><span class="eyebrow">PAKET</span><h2>Mulai kecil, tetap siap tumbuh</h2></div><div class="pricing-grid"><article><h3>Free</h3><strong>Rp0</strong><p>Untuk mencoba alur inti satu outlet.</p></article><article class="featured"><span>Paling fleksibel</span><h3>Growth</h3><strong>Harga Anda</strong><p>Multi-cabang, laporan, dan integrasi sesuai kebutuhan.</p></article><article><h3>Whitelabel</h3><strong>Konsultasi</strong><p>Brand, domain, modul, dan deployment mandiri.</p></article></div></div></section>
<section class="final-cta"><div class="public-container reveal"><span class="eyebrow">SIAP MERAPIKAN OPERASIONAL?</span><h2>Lihat PanduPOS bekerja dengan data demo.</h2><div class="hero-actions"><a class="button button-light" href="{{ route('login') }}">Coba Demo</a><a class="button button-outline-light" href="{{ route('docs') }}">Pelajari Alur</a></div></div></section>
@endsection
