@extends('layouts.tabler')
@section('title','Barcode & Label')
@section('header','Barcode & Label')
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row row-cards">
<div class="col-12 col-xl-5"><div class="card"><div class="card-header"><h2 class="card-title">Profil barcode timbangan</h2></div><form class="card-body row g-3" method="POST" action="{{ route('barcodes.profiles.store') }}">@csrf
<div class="col-8"><label class="form-label">Nama profil</label><input class="form-control" name="name" required placeholder="Timbangan deli"></div><div class="col-4"><label class="form-label">Prefix</label><input class="form-control" name="prefix" required placeholder="20"></div>
@foreach(['total_length'=>'Panjang total','item_start'=>'Posisi item','item_length'=>'Panjang item','value_start'=>'Posisi nilai','value_length'=>'Panjang nilai','decimal_places'=>'Desimal'] as $name=>$label)<div class="col-4"><label class="form-label">{{ $label }}</label><input class="form-control" type="number" min="0" name="{{ $name }}" required value="{{ $name==='total_length'?13:($name==='decimal_places'?3:0) }}"></div>@endforeach
<div class="col-6"><label class="form-label">Makna nilai</label><select class="form-select" name="value_type"><option value="weight">Berat</option><option value="price">Harga</option></select></div><div class="col-6 d-flex align-items-end"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><span class="form-check-label">Aktif</span></label></div>
<div class="col-12"><button class="btn btn-primary w-100">Simpan profil</button></div></form></div></div>
<div class="col-12 col-xl-7"><div class="card"><div class="card-header"><h2 class="card-title">Profil aktif</h2></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Profil</th><th>Format</th><th>Nilai</th><th>Status</th><th></th></tr></thead><tbody>@forelse($profiles as $profile)<tr><td>{{ $profile->name }}<div class="text-secondary">Prefix {{ $profile->prefix }}</div></td><td>{{ $profile->total_length }} digit · item {{ $profile->item_start }}+{{ $profile->item_length }} · nilai {{ $profile->value_start }}+{{ $profile->value_length }}</td><td>{{ $profile->value_type }} / {{ $profile->decimal_places }} desimal</td><td>{{ $profile->is_active?'Aktif':'Nonaktif' }}</td><td>@if($profile->is_active)<form method="POST" action="{{ route('barcodes.profiles.archive',$profile) }}">@csrf<button class="btn btn-sm btn-outline-danger">Nonaktifkan</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Belum ada profil.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-12 col-lg-5"><div class="card"><div class="card-header"><h2 class="card-title">Uji parser</h2></div><form class="card-body" method="GET"><label class="form-label">Scan / masukkan barcode</label><div class="input-group"><input class="form-control" name="barcode" value="{{ request('barcode') }}" required><button class="btn btn-secondary">Parse</button></div>@if($parsed)<div class="alert alert-info mt-3 mb-0"><strong>{{ $parsed['type'] }}</strong> · {{ $parsed['variant']->sku }} @if($parsed['quantity'])· qty {{ $parsed['quantity'] }}@endif @if($parsed['price'])· Rp {{ number_format($parsed['price'],2,',','.') }}@endif</div>@endif</form></div></div>
<div class="col-12 col-lg-7"><div class="card"><div class="card-header"><h2 class="card-title">Cetak label Code 128</h2></div><form class="card-body row g-3" method="GET" action="{{ route('barcodes.labels') }}" target="_blank"><div class="col-12"><label class="form-label">Varian (Ctrl/⌘ untuk multi pilih)</label><select class="form-select" name="variants[]" multiple size="6" required>@foreach($variants as $variant)<option value="{{ $variant->id }}" @disabled(!$variant->barcode)>{{ $variant->sku }} · {{ $variant->product?->name }} · {{ $variant->barcode ?: 'barcode belum diisi' }}</option>@endforeach</select></div><div class="col-4"><label class="form-label">Jumlah/varian</label><input class="form-control" type="number" name="quantity" min="1" max="200" value="1" required></div><div class="col-4"><label class="form-label">Template</label><select class="form-select" name="template"><option value="a4">A4 sheet</option><option value="thermal">Thermal</option></select></div><div class="col-4 d-flex align-items-end"><button class="btn btn-primary w-100">Preview cetak</button></div></form></div></div>
</div>
@endsection
