@extends('layouts.tabler')
@section('title', 'Provider Integrasi — PanduPOS')
@section('header', 'Integrasi · Provider Dinamis')
@section('content')
<div class="row row-cards"><div class="col-xl-5"><div class="card"><div class="card-header"><h3 class="card-title">Tambah provider</h3></div><div class="card-body"><p class="text-secondary">Nama, endpoint, key, dan format sepenuhnya ditentukan operator. Key disimpan terenkripsi dan tidak pernah ditampilkan kembali.</p><form method="POST" action="{{ route('platform.integrations.store') }}">@csrf
<div class="mb-3"><label class="form-label">Nama provider</label><input class="form-control" name="name" required></div>
<div class="mb-3"><label class="form-label">Tenant (kosong = global)</label><select class="form-select" name="tenant_id"><option value="">Global platform</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}">{{ $tenant->name }}</option>@endforeach</select></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Jenis integrasi</label><select class="form-select" name="integration_type" required>@foreach(['payment'=>'Pembayaran','notification'=>'Notifikasi','storage'=>'Penyimpanan','webhook'=>'Webhook','ai'=>'AI'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Format API</label><select class="form-select" name="api_format" required>@foreach(['redirect','embedded','qr','rest','openai_compatible','anthropic_format','gemini_format'] as $format)<option value="{{ $format }}">{{ $format }}</option>@endforeach</select></div></div>
<div class="mb-3"><label class="form-label">Base URL</label><input class="form-control" type="url" name="base_url" placeholder="https://endpoint-anda.example"></div><div class="mb-3"><label class="form-label">API key (opsional)</label><input class="form-control" type="password" name="api_key_encrypted" autocomplete="new-password"></div><div class="mb-3"><label class="form-label">Header tambahan (JSON)</label><textarea class="form-control font-monospace" name="extra_headers" rows="3" placeholder='{"X-Client":"nilai"}'></textarea></div><div class="mb-3"><label class="form-label">Pengaturan format (JSON)</label><textarea class="form-control font-monospace" name="settings" rows="6" placeholder='{"request_path":"v1/request","models_path":"v1/models"}'></textarea></div><label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><span class="form-check-label">Aktif</span></label><button class="btn btn-primary w-100">Simpan provider</button></form></div></div></div>
<div class="col-xl-7"><div class="card"><div class="card-header"><h3 class="card-title">Provider terdaftar</h3></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Provider</th><th>Jenis</th><th>Format</th><th>Status</th><th></th></tr></thead><tbody>@forelse($providers as $provider)<tr><td><strong>{{ $provider->name }}</strong><div class="text-secondary text-truncate" style="max-width:220px">{{ $provider->base_url ?: 'Endpoint belum diisi' }}</div><small>{{ $provider->tenant?->name ?? 'Global' }}</small></td><td>{{ $provider->integration_type }}</td><td><code>{{ $provider->api_format }}</code></td><td><span class="badge {{ $provider->is_active ? 'bg-green-lt' : 'bg-secondary-lt' }}">{{ $provider->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="d-flex gap-1">@if($provider->api_format === 'openai_compatible')<form method="POST" action="{{ route('platform.integrations.discover',$provider) }}">@csrf<button class="btn btn-sm btn-outline-primary">Fetch models</button></form>@endif<form method="POST" action="{{ route('platform.integrations.destroy',$provider) }}" onsubmit="return confirm('Hapus provider ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></div></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Belum ada provider. Tambahkan provider dengan konfigurasi Anda sendiri.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $providers->links() }}</div></div></div></div>
@if(session('discovered_models'))<div class="alert alert-info mt-3"><strong>Model ditemukan:</strong> {{ implode(', ', session('discovered_models')) }}</div>@endif
<div class="card mt-3"><div class="card-header"><h3 class="card-title">Provider per fitur</h3></div><div class="card-body"><p class="text-secondary">Daftar kosong secara default. Nama fitur, model, dan tarif sepenuhnya diisi operator.</p><form method="POST" action="{{ route('platform.integrations.assign') }}">@csrf<div class="row"><div class="col-md-3 mb-3"><label class="form-label">Tenant</label><select class="form-select" name="tenant_id" required>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}">{{ $tenant->name }}</option>@endforeach</select></div><div class="col-md-3 mb-3"><label class="form-label">Kunci fitur</label><input class="form-control" name="feature_key" placeholder="contoh: ringkasan_laporan" required></div><div class="col-md-3 mb-3"><label class="form-label">Provider</label><select class="form-select" name="integration_provider_id" required><option value="">Pilih provider</option>@foreach($allProviders as $provider)<option value="{{ $provider->id }}">{{ $provider->name }} · {{ $provider->api_format }}</option>@endforeach</select></div><div class="col-md-3 mb-3"><label class="form-label">Model/endpoint</label><input class="form-control" name="model_name"></div><div class="col-md-3 mb-3"><label class="form-label">Tarif input</label><input class="form-control" type="number" step="0.00000001" min="0" name="input_rate"></div><div class="col-md-3 mb-3"><label class="form-label">Tarif output</label><input class="form-control" type="number" step="0.00000001" min="0" name="output_rate"></div></div><button class="btn btn-primary">Simpan pemetaan</button></form></div><div class="table-responsive"><table class="table"><thead><tr><th>Tenant</th><th>Fitur</th><th>Provider</th><th>Model</th><th>Tarif input/output</th></tr></thead><tbody>@forelse($assignments as $assignment)<tr><td>{{ $assignment->tenant->name }}</td><td><code>{{ $assignment->feature_key }}</code></td><td>{{ $assignment->provider->name }}</td><td>{{ $assignment->model_name ?: '—' }}</td><td>{{ $assignment->input_rate ?? '—' }} / {{ $assignment->output_rate ?? '—' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Belum ada pemetaan fitur.</td></tr>@endforelse</tbody></table></div></div>
@endsection
