@extends('layouts.public')
@section('title', 'Dokumentasi PanduPOS — Tutorial Operasional Lengkap')
@section('description', 'Panduan langkah demi langkah PanduPOS: setup, master data, pembelian, POS, stok, keamanan, finance, dan laporan.')
@section('content')
<section class="page-hero"><div class="public-container"><span class="eyebrow">DOKUMENTASI PRODUK</span><h1>Dari setup sampai laporan, tanpa langkah yang terlewat.</h1><p>Ikuti alur bisnis PanduPOS dalam {{ $tutorialStepCount }} langkah. Halaman ini merangkum akses demo, struktur fungsi, tutorial, dan manfaat tiap kelompok fitur.</p></div></section>
<nav class="jump-nav" aria-label="Navigasi dokumentasi"><div class="public-container"><a href="#akun">Akun Demo</a><a href="#menu">Struktur Menu</a><a href="#tutorial">Tutorial</a><a href="#fitur">Fitur Lengkap</a><a href="#mulai">Mulai</a></div></nav>
<section id="akun" class="section"><div class="public-container"><div class="section-heading"><span class="eyebrow">AKUN DEMO</span><h2>Akses sesuai tanggung jawab</h2></div><div class="table-wrap"><table class="public-table"><thead><tr><th>Role</th><th>Email</th><th>Password</th><th>Cakupan</th></tr></thead><tbody>@foreach($accounts as $account)<tr><td>{{ $account['role'] }}</td><td><code>{{ $account['email'] }}</code></td><td><code>{{ $account['password'] }}</code></td><td>{{ $account['scope'] }}</td></tr>@endforeach</tbody></table></div></div></section>
<section id="menu" class="section section-muted"><div class="public-container"><div class="section-heading"><span class="eyebrow">STRUKTUR MENU</span><h2>Menu mengikuti alur bisnis</h2></div><div class="feature-grid">@foreach([['Master Data','Produk, kategori, merek, satuan, pelanggan, pemasok'],['Penjualan','POS, invoice, pembayaran, retur, void'],['Persediaan','Gudang, transfer, mutasi, stok minimum'],['Finance & Laporan','Billing, laba, penjualan, valuasi stok'],['Platform SaaS','Tenant, plan, subscription, entitlement'],['Marketing','Blog, kupon, afiliasi, announcement'],['Integrasi','API, sync, webhook, branding'],['Sistem','User, role, audit, health check']] as [$group,$items])<article class="feature-card"><h3>{{ $group }}</h3><p>{{ $items }}</p></article>@endforeach</div></div></section>
<section id="tutorial" class="section"><div class="public-container"><div class="section-heading"><span class="eyebrow">TUTORIAL {{ $tutorialStepCount }} LANGKAH</span><h2>Alur kerja dari awal hingga analisis</h2></div>@foreach($phases as $index => $phase)<article class="tutorial-phase reveal"><div><span class="eyebrow">FASE {{ $index + 1 }}</span><h3>{{ $phase['title'] }}</h3></div><ol>@foreach($phase['steps'] as $step)<li>{{ $step }}</li>@endforeach</ol></article>@endforeach</div></section>
<section id="fitur" class="section section-muted"><div class="public-container"><div class="section-heading"><span class="eyebrow">FITUR LENGKAP</span><h2>Apa yang dikerjakan setiap modul</h2></div>@foreach($features as $feature)<article class="doc-feature reveal"><div class="browser-shot"><div class="browser-bar"><i></i><i></i><i></i><small>{{ $feature['url'] }}</small></div><img src="{{ asset('marketing/screens/'.$feature['screenshot']) }}" alt="{{ $feature['title'] }}" loading="lazy"></div><div><span class="eyebrow">{{ strtoupper($feature['group']) }}</span><h2>{{ $feature['title'] }}</h2><p class="prose">{{ $feature['description'] }}</p><ul>@foreach($feature['bullets'] as $bullet)<li>{{ $bullet }}</li>@endforeach</ul></div></article>@endforeach</div></section>
<section id="mulai" class="final-cta"><div class="public-container"><span class="eyebrow">COBA SEKARANG</span><h2>Masuk ke tenant demo dan ikuti tutorialnya.</h2><div class="hero-actions"><a class="button button-light" href="{{ route('login') }}">Buka Admin</a><a class="button button-outline-light" href="{{ route('home') }}">Kembali ke Produk</a></div></div></section>
@endsection
