@extends('layouts.tabler')

@section('title', 'Purchase Return')
@section('page-title', 'Purchase Return')
@section('page-subtitle', 'PO #'.$purchase->id.' · '.$purchase->contact?->name)

@section('content')
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><div class="card-header"><h2 class="card-title">Kembalikan barang yang telah diterima</h2></div><form method="POST" action="{{ route('purchasing.returns.store', $purchase) }}">@csrf<div class="card-body"><p class="text-secondary">Setiap baris wajib berasal dari PO ini. Batch dan rak/bin bersifat optional, tetapi bila dipilih harus berasal dari GRN PO dan memiliki stok tersedia.</p><div id="return-lines" class="vstack gap-3">
<div class="border rounded p-3 return-line"><div class="row g-2 align-items-end"><div class="col-12 col-lg-4"><label class="form-label">Produk</label><select name="lines[0][purchase_line_id]" class="form-select">@foreach($purchase->lines as $option)<option value="{{ $option->id }}">{{ $option->variant?->sku }} · diterima {{ number_format((float)$option->received_quantity,3) }}</option>@endforeach</select></div><div class="col-6 col-lg-2"><label class="form-label">Jumlah</label><input name="lines[0][quantity]" type="number" min="0.001" step="0.001" class="form-control" required></div><div class="col-6 col-lg-3"><label class="form-label">Batch asal</label><select name="lines[0][inventory_batch_id]" class="form-select"><option value="">Tanpa batch</option>@foreach($purchase->lines as $line)@foreach($line->goodsReceiptLines->pluck('batch')->filter()->unique('id') as $batch)<option value="{{ $batch->id }}">{{ $batch->batch_number }}</option>@endforeach @endforeach</select></div><div class="col-12 col-lg-3"><label class="form-label">Rak/bin asal</label><select name="lines[0][warehouse_location_id]" class="form-select"><option value="">Tanpa rak/bin</option>@foreach($purchase->lines as $line)@foreach($line->goodsReceiptLines->pluck('warehouseLocation')->filter()->unique('id') as $location)<option value="{{ $location->id }}">{{ $location->code }}</option>@endforeach @endforeach</select></div></div></div>
</div><div class="row g-3 mt-1"><div class="col-12 col-md-6"><label class="form-label">Penyelesaian</label><select name="settlement_type" class="form-select"><option value="supplier_credit">Kredit pemasok</option><option value="cash_refund">Refund tunai</option><option value="replacement">Penggantian</option></select></div><div class="col-12"><label class="form-label">Alasan wajib</label><textarea name="reason" class="form-control" rows="3" required></textarea></div></div></div><div class="col-12 col-md-6"><label class="form-label">Kunci idempotensi (opsional)</label><input name="idempotency_key" class="form-control" maxlength="128" placeholder="Cegah double posting"></div><div class="col-6 col-md-3"><label class="form-label">Pajak</label><input name="tax" type="number" min="0" step="0.01" value="0" class="form-control"></div><div class="col-6 col-md-3"><label class="form-label">Diskon</label><input name="discount" type="number" min="0" step="0.01" value="0" class="form-control"></div></div></div><div class="card-footer d-flex flex-wrap gap-2 justify-content-between"><a href="{{ route('purchasing.index') }}" class="btn btn-outline-secondary">Batal</a><div class="d-flex gap-2"><button class="btn btn-outline-primary" formaction="{{ route('purchasing.returns.draft', $purchase) }}">Simpan sebagai draft</button><button class="btn btn-danger">Posting purchase return</button></div></div></form></div>
@endsection
