@extends('layouts.tabler')
@section('title', $title.' — PanduPOS')
@section('header', $title)
@section('content')
<div class="report-toolbar card mb-3"><div class="card-body"><form class="row g-3 align-items-end" method="GET"><div class="col-sm-6 col-lg-2"><label class="form-label">Dari</label><input class="form-control" type="date" name="from" value="{{ $from }}"></div><div class="col-sm-6 col-lg-2"><label class="form-label">Sampai</label><input class="form-control" type="date" name="to" value="{{ $to }}"></div><div class="col-sm-6 col-lg-2"><label class="form-label">Kelompok</label><select class="form-select" name="group"><option value="daily" @selected($group==='daily')>Harian</option><option value="weekly" @selected($group==='weekly')>Mingguan</option><option value="monthly" @selected($group==='monthly')>Bulanan</option></select></div><div class="col-sm-6 col-lg-2"><label class="form-label">Cabang</label><select class="form-select" name="branch_id"><option value="">Semua</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branch->id === $branchId)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-sm-6 col-lg-2"><label class="form-label">Gudang</label><select class="form-select" name="warehouse_id"><option value="">Semua</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected($warehouse->id === $warehouseId)>{{ $warehouse->name }}</option>@endforeach</select></div><div class="col-12 col-lg-2 d-flex gap-2 flex-wrap"><button class="btn btn-primary">Terapkan</button><a class="btn btn-outline-success" href="{{ route('reports.csv',[$type,'from'=>$from,'to'=>$to,'group'=>$group,'branch_id'=>$branchId,'warehouse_id'=>$warehouseId]) }}">CSV</a><a class="btn btn-outline-primary" href="{{ route('reports.xlsx',[$type,'from'=>$from,'to'=>$to,'group'=>$group,'branch_id'=>$branchId,'warehouse_id'=>$warehouseId]) }}">Excel</a><a class="btn btn-outline-danger" href="{{ route('reports.pdf',[$type,'from'=>$from,'to'=>$to,'group'=>$group,'branch_id'=>$branchId,'warehouse_id'=>$warehouseId]) }}">PDF</a></div></form></div></div>
<div class="report-switcher mb-3"><a class="btn {{ $type==='bisnis'?'btn-dark':'btn-outline-secondary' }}" href="{{ route('reports.show','bisnis') }}">Bisnis</a><a class="btn {{ $type==='keuangan'?'btn-dark':'btn-outline-secondary' }}" href="{{ route('reports.show','keuangan') }}">Keuangan</a><a class="btn {{ $type==='operasional'?'btn-dark':'btn-outline-secondary' }}" href="{{ route('reports.show','operasional') }}">Operasional</a></div>
@php($currencyLabels = ['Omzet', 'Rata-rata transaksi', 'Lunas', 'Pendapatan', 'COGS', 'Laba kotor', 'Nilai pembelian', 'Valuasi stok'])
<div class="row row-cards mb-3">@foreach($summary as $label=>$value)<div class="col-sm-6 col-xl"><div class="card report-stat"><div class="card-body"><div class="subheader">{{ $label }}</div><div class="h2 mb-0">{{ str_contains($label, '%') ? number_format((float) $value, 1, ',', '.').'%' : (in_array($label, $currencyLabels, true) ? 'Rp '.number_format((float) $value, 0, ',', '.') : number_format((float) $value, 0, ',', '.')) }}</div></div></div></div>@endforeach</div>
<div class="card mb-3"><div class="card-header"><h3 class="card-title">Tren periode</h3><div class="card-actions text-secondary">Auto-refresh 60 detik</div></div><div class="card-body"><div class="chart-shell"><canvas id="report-chart" aria-label="Grafik {{ $title }}"></canvas></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Detail data</h3></div><div class="table-responsive"><table class="table table-vcenter table-hover"><thead><tr>@foreach($columns as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>@forelse($rows as $row)<tr>@foreach($row as $value)<td>{{ is_float($value) ? number_format($value,2,',','.') : $value }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($columns) }}" class="text-center text-secondary py-5">Belum ada data pada rentang ini.</td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
new Chart(document.getElementById('report-chart'), {type:'bar',data:{labels:@json($chart['labels']),datasets:[{label:@json($title),data:@json($chart['values']),backgroundColor:'rgba(8,122,84,.75)',borderColor:'#087a54',borderWidth:1,borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'rgba(20,35,28,.08)'}},x:{grid:{display:false}}}}});
setTimeout(() => window.location.reload(), 60000);
</script>
@endpush
