@extends('layouts.tabler')
@php($editing = $product->exists)
@section('title', $editing ? 'Edit Produk' : 'Produk Baru')
@section('header', $editing ? 'Edit Produk' : 'Produk Baru')
@section('content')
<form method="POST" enctype="multipart/form-data" action="{{ $editing ? route('product-master.update',$product) : route('product-master.store') }}">@csrf @if($editing)@method('PUT')@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Periksa kembali isian.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row row-cards"><div class="col-12 col-xl-8"><div class="card"><div class="card-header"><h3 class="card-title">Informasi produk</h3></div><div class="card-body"><div class="row g-3">
<div class="col-12 col-md-8"><label class="form-label" for="name">Nama produk</label><input id="name" class="form-control" name="name" required value="{{ old('name',$product->name) }}"></div>
<div class="col-12 col-md-4"><label class="form-label" for="product_type">Tipe</label><select id="product_type" class="form-select" name="product_type" required>@foreach(['stock'=>'Stok','service'=>'Jasa','bundle'=>'Bundle / Combo'] as $value=>$label)<option value="{{ $value }}" @selected(old('product_type',$product->product_type ?: 'stock')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12 col-md-6"><label class="form-label" for="sku">SKU induk</label><input id="sku" class="form-control" name="sku" value="{{ old('sku',$product->sku) }}"></div><div class="col-12 col-md-6"><label class="form-label" for="barcode">Barcode produk</label><input id="barcode" class="form-control" name="barcode" value="{{ old('barcode',$product->barcode) }}"></div>
<div class="col-12 col-md-4"><label class="form-label" for="category_id">Kategori</label><select id="category_id" class="form-select" name="category_id"><option value="">—</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id',$product->category_id)===(string)$category->id)>{{ $category->parent ? $category->parent->name.' / ' : '' }}{{ $category->name }}</option>@endforeach</select></div>
<div class="col-12 col-md-4"><label class="form-label" for="brand_id">Merek</label><select id="brand_id" class="form-select" name="brand_id"><option value="">—</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((string)old('brand_id',$product->brand_id)===(string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
<div class="col-12 col-md-4"><label class="form-label" for="unit_id">Satuan dasar</label><select id="unit_id" class="form-select" name="unit_id"><option value="">—</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string)old('unit_id',$product->unit_id)===(string)$unit->id)>{{ $unit->name }} ({{ $unit->short_name }})</option>@endforeach</select></div>
<div class="col-6 col-md-3"><label class="form-label" for="alert_quantity">Reorder level</label><input id="alert_quantity" class="form-control" type="number" step="0.001" min="0" name="alert_quantity" required value="{{ old('alert_quantity',$product->alert_quantity ?? 0) }}"></div>
<div class="col-6 col-md-3"><label class="form-label" for="tax_rate">Pajak %</label><input id="tax_rate" class="form-control" type="number" step="0.0001" min="0" max="100" name="tax_rate" required value="{{ old('tax_rate',$product->tax_rate ?? 0) }}"></div>
<div class="col-12 col-md-3"><label class="form-label" for="tax_method">Metode pajak</label><select id="tax_method" class="form-select" name="tax_method">@foreach(['exclusive'=>'Eksklusif','inclusive'=>'Inklusif','zero'=>'Tarif nol','exempt'=>'Bebas'] as $value=>$label)<option value="{{ $value }}" @selected(old('tax_method',$product->tax_method ?: 'exclusive')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12 col-md-3"><label class="form-label" for="image">Gambar (maks. 2 MB)</label><input id="image" class="form-control" type="file" accept="image/*" name="image"></div>
<div class="col-12"><div class="form-check form-switch"><input type="hidden" name="track_inventory" value="0"><input class="form-check-input" id="track_inventory" type="checkbox" name="track_inventory" value="1" @checked(old('track_inventory',$product->exists ? $product->track_inventory : true))><label class="form-check-label" for="track_inventory">Lacak persediaan</label></div><div class="form-check form-switch mt-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="is_active" type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->exists ? $product->is_active : true))><label class="form-check-label" for="is_active">Produk aktif</label></div></div>
</div></div></div>
<div class="card mt-4"><div class="card-header d-flex justify-content-between"><h3 class="card-title">Varian & atribut</h3><button class="btn btn-sm btn-outline-primary" type="button" id="add-variant">Tambah varian</button></div><div class="card-body" id="variants">
@php($variantRows = old('variants', $product->exists ? $product->variants->map(fn($v)=>['id'=>$v->id,'name'=>$v->name,'sku'=>$v->sku,'barcode'=>$v->barcode,'purchase_price'=>$v->purchase_price,'sell_price'=>$v->sell_price,'attributes_text'=>collect($v->attributes)->map(fn($value,$key)=>$key.': '.$value)->implode("\n")])->all() : [['name'=>'Default','sku'=>'','barcode'=>'','purchase_price'=>0,'sell_price'=>0,'attributes_text'=>'']]))
@foreach($variantRows as $i=>$variant)<div class="variant-row border rounded p-3 mb-3"><input type="hidden" name="variants[{{ $i }}][id]" value="{{ $variant['id'] ?? '' }}"><div class="row g-3"><div class="col-12 col-md-4"><label class="form-label">Nama varian</label><input class="form-control" name="variants[{{ $i }}][name]" required value="{{ $variant['name'] }}"></div><div class="col-6 col-md-4"><label class="form-label">SKU</label><input class="form-control" name="variants[{{ $i }}][sku]" value="{{ $variant['sku'] }}"></div><div class="col-6 col-md-4"><label class="form-label">Barcode</label><input class="form-control" name="variants[{{ $i }}][barcode]" value="{{ $variant['barcode'] }}"></div><div class="col-6 col-md-3"><label class="form-label">Harga beli</label><input class="form-control" type="number" min="0" step="0.01" name="variants[{{ $i }}][purchase_price]" required value="{{ $variant['purchase_price'] }}"></div><div class="col-6 col-md-3"><label class="form-label">Harga jual</label><input class="form-control" type="number" min="0" step="0.01" name="variants[{{ $i }}][sell_price]" required value="{{ $variant['sell_price'] }}"></div><div class="col-12 col-md-5"><label class="form-label">Atribut (satu per baris: Nama: Nilai)</label><textarea class="form-control" rows="2" name="variants[{{ $i }}][attributes_text]">{{ $variant['attributes_text'] }}</textarea></div><div class="col-12 col-md-1 d-flex align-items-end"><button class="btn btn-outline-danger remove-variant w-100" type="button" aria-label="Hapus varian">×</button></div></div></div>@endforeach
</div></div></div>
<div class="col-12 col-xl-4"><div class="card"><div class="card-header"><h3 class="card-title">Lokasi produk</h3></div><div class="card-body"><p class="text-secondary">Pilih gudang/cabang yang boleh menjual atau menyimpan produk ini.</p>@forelse($warehouses as $warehouse)<label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="warehouse_ids[]" value="{{ $warehouse->id }}" @checked(in_array($warehouse->id,old('warehouse_ids',$product->exists ? $product->locations->where('is_active',true)->pluck('warehouse_id')->all() : [])))><span class="form-check-label">{{ $warehouse->name }} <small class="d-block text-secondary">{{ $warehouse->code }}</small></span></label>@empty<div class="alert alert-warning">Buat gudang terlebih dahulu.</div>@endforelse</div></div>
<div class="card mt-4"><div class="card-body"><button class="btn btn-primary w-100" type="submit">{{ $editing ? 'Simpan perubahan' : 'Buat produk' }}</button><a class="btn btn-link w-100 mt-2" href="{{ route('product-master.index') }}">Batal</a></div></div></div></div></form>
@push('scripts')<script>
(()=>{const box=document.getElementById('variants');const add=document.getElementById('add-variant');let i=box.querySelectorAll('.variant-row').length;add.addEventListener('click',()=>{const row=document.createElement('div');row.className='variant-row border rounded p-3 mb-3';row.innerHTML=`<div class="row g-3"><div class="col-12 col-md-4"><label class="form-label">Nama varian</label><input class="form-control" name="variants[${i}][name]" required></div><div class="col-6 col-md-4"><label class="form-label">SKU</label><input class="form-control" name="variants[${i}][sku]"></div><div class="col-6 col-md-4"><label class="form-label">Barcode</label><input class="form-control" name="variants[${i}][barcode]"></div><div class="col-6 col-md-3"><label class="form-label">Harga beli</label><input class="form-control" type="number" min="0" step=".01" name="variants[${i}][purchase_price]" required value="0"></div><div class="col-6 col-md-3"><label class="form-label">Harga jual</label><input class="form-control" type="number" min="0" step=".01" name="variants[${i}][sell_price]" required value="0"></div><div class="col-12 col-md-5"><label class="form-label">Atribut</label><textarea class="form-control" rows="2" name="variants[${i}][attributes_text]"></textarea></div><div class="col-12 col-md-1 d-flex align-items-end"><button class="btn btn-outline-danger remove-variant w-100" type="button" aria-label="Hapus varian">×</button></div></div>`;box.appendChild(row);i++;});box.addEventListener('click',e=>{if(e.target.closest('.remove-variant')&&box.querySelectorAll('.variant-row').length>1)e.target.closest('.variant-row').remove();});})();
</script>@endpush
@endsection
