@extends('layouts.tabler')
@section('title', 'Master Produk')
@section('header', 'Master Produk')
@section('content')
<div class="d-flex flex-column flex-sm-row justify-content-between gap-3 align-items-sm-center mb-4">
    <div><h2 class="page-title">Produk & Katalog</h2><p class="text-secondary mb-0">Kelola produk, varian, kategori, merek, satuan, dan lokasi penjualan.</p></div>
    <a class="btn btn-primary" href="{{ route('product-master.create') }}"><span aria-hidden="true">＋</span> Produk baru</a>
</div>
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Data belum tersimpan.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="row row-cards mb-4">
    <div class="col-12 col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title">Kategori / Subkategori</h3></div><form class="card-body" method="POST" action="{{ route('product-master.categories.store') }}">@csrf
        <label class="form-label" for="category-name">Nama</label><input id="category-name" class="form-control mb-3" name="name" required maxlength="255">
        <label class="form-label" for="category-parent">Induk (opsional)</label><select id="category-parent" class="form-select mb-3" name="parent_id"><option value="">Kategori utama</option>@foreach($categories->whereNull('parent_id') as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>
        <button class="btn btn-outline-primary w-100" type="submit">Simpan kategori</button></form></div></div>
    <div class="col-12 col-md-6 col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title">Merek</h3></div><form class="card-body" method="POST" action="{{ route('product-master.brands.store') }}">@csrf
        <label class="form-label" for="brand-name">Nama merek</label><input id="brand-name" class="form-control mb-3" name="name" required maxlength="255"><button class="btn btn-outline-primary w-100" type="submit">Simpan merek</button></form></div></div>
    <div class="col-12 col-md-6 col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title">Satuan</h3></div><form class="card-body" method="POST" action="{{ route('product-master.units.store') }}">@csrf
        <div class="row g-3"><div class="col-8"><label class="form-label" for="unit-name">Nama</label><input id="unit-name" class="form-control" name="name" required></div><div class="col-4"><label class="form-label" for="unit-short">Singkatan</label><input id="unit-short" class="form-control" name="short_name" required maxlength="16"></div></div><button class="btn btn-outline-primary w-100 mt-3" type="submit">Simpan satuan</button></form></div></div>
</div>

<div class="card mb-4"><div class="card-header"><h3 class="card-title">Master katalog aktif dan arsip</h3></div><div class="card-body"><div class="row g-4">
<div class="col-12 col-lg-4"><h4>Kategori</h4><div class="vstack gap-2">@forelse($categories as $category)<div class="border rounded p-2"><form class="d-flex gap-2" method="POST" action="{{ route('product-master.categories.update',$category) }}">@csrf @method('PUT')<input class="form-control form-control-sm" name="name" value="{{ $category->name }}" aria-label="Nama kategori"><button class="btn btn-sm btn-outline-primary">Simpan</button></form><div class="d-flex justify-content-between align-items-center mt-2"><small class="text-secondary">{{ $category->parent?->name ? 'Induk: '.$category->parent->name : 'Kategori utama' }} · {{ $category->is_active ? 'Aktif' : 'Nonaktif' }}</small>@if($category->is_active)<form method="POST" action="{{ route('product-master.masters.archive',['type'=>'category','id'=>$category->id]) }}">@csrf<button class="btn btn-sm btn-link text-danger">Nonaktifkan</button></form>@endif</div></div>@empty<p class="text-secondary">Belum ada kategori.</p>@endforelse</div></div>
<div class="col-12 col-lg-4"><h4>Merek</h4><div class="vstack gap-2">@forelse($brands as $brand)<div class="border rounded p-2"><form class="d-flex gap-2" method="POST" action="{{ route('product-master.brands.update',$brand) }}">@csrf @method('PUT')<input class="form-control form-control-sm" name="name" value="{{ $brand->name }}" aria-label="Nama merek"><button class="btn btn-sm btn-outline-primary">Simpan</button></form><div class="d-flex justify-content-between align-items-center mt-2"><small class="text-secondary">{{ $brand->is_active ? 'Aktif' : 'Nonaktif' }}</small>@if($brand->is_active)<form method="POST" action="{{ route('product-master.masters.archive',['type'=>'brand','id'=>$brand->id]) }}">@csrf<button class="btn btn-sm btn-link text-danger">Nonaktifkan</button></form>@endif</div></div>@empty<p class="text-secondary">Belum ada merek.</p>@endforelse</div></div>
<div class="col-12 col-lg-4"><h4>Satuan</h4><div class="vstack gap-2">@forelse($units as $unit)<div class="border rounded p-2"><form class="d-flex gap-2" method="POST" action="{{ route('product-master.units.update',$unit) }}">@csrf @method('PUT')<input class="form-control form-control-sm" name="name" value="{{ $unit->name }}" aria-label="Nama satuan"><input class="form-control form-control-sm" style="max-width:5rem" name="short_name" value="{{ $unit->short_name }}" aria-label="Singkatan"><button class="btn btn-sm btn-outline-primary">Simpan</button></form><div class="d-flex justify-content-between align-items-center mt-2"><small class="text-secondary">{{ $unit->is_active ? 'Aktif' : 'Nonaktif' }}</small>@if($unit->is_active)<form method="POST" action="{{ route('product-master.masters.archive',['type'=>'unit','id'=>$unit->id]) }}">@csrf<button class="btn btn-sm btn-link text-danger">Nonaktifkan</button></form>@endif</div></div>@empty<p class="text-secondary">Belum ada satuan.</p>@endforelse</div></div>
</div></div></div>

<div class="card"><div class="card-header"><form class="row g-2 w-100" method="GET"><div class="col-12 col-md"><label class="visually-hidden" for="search">Cari produk</label><input id="search" class="form-control" name="search" value="{{ request('search') }}" placeholder="Cari nama, SKU, atau barcode"></div><div class="col-8 col-md-3"><select class="form-select" name="status" aria-label="Status"><option value="">Semua status</option><option value="active" @selected(request('status')==='active')>Aktif</option><option value="inactive" @selected(request('status')==='inactive')>Nonaktif</option></select></div><div class="col-4 col-md-auto"><button class="btn btn-secondary w-100">Filter</button></div></form></div>
<div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Produk</th><th>Tipe</th><th>Kategori</th><th>Varian</th><th>Lokasi</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($products as $product)<tr><td><div class="fw-semibold">{{ $product->name }}</div><small class="text-secondary">{{ $product->sku ?: 'Tanpa SKU' }} · {{ $product->barcode ?: 'Tanpa barcode' }}</small></td><td>{{ ucfirst($product->product_type) }}</td><td>{{ $product->category?->name ?? '—' }}</td><td>{{ $product->variants->where('is_active', true)->count() }}</td><td>{{ $product->locations->where('is_active', true)->count() }}</td><td><span class="badge {{ $product->is_active ? 'bg-success-lt' : 'bg-secondary-lt' }}">{{ $product->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="text-end"><div class="btn-list justify-content-end flex-nowrap"><a class="btn btn-sm" href="{{ route('product-master.show',$product) }}">Lihat</a><a class="btn btn-sm btn-outline-primary" href="{{ route('product-master.edit',$product) }}">Edit</a></div></td></tr>
@empty<tr><td colspan="7"><div class="empty py-5"><p class="empty-title">Belum ada produk</p><p class="empty-subtitle text-secondary">Tambahkan kategori dan satuan, lalu buat produk pertama.</p><a class="btn btn-primary" href="{{ route('product-master.create') }}">Buat produk</a></div></td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{ $products->links() }}</div></div>
@endsection
