@extends('layouts.tabler')

@section('title', 'Quotation')
@section('header', 'Quotation')

@section('content')
@if(session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row row-cards">
    <div class="col-12 col-xl-4"><div class="card"><div class="card-header"><h2 class="card-title">Buat quotation</h2></div><form class="card-body row g-3" method="POST" action="{{ route('sales-documents.quotations.store') }}">@csrf
        <div class="col-12"><label class="form-label">Cabang</label><select name="branch_id" class="form-select" required>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div>
        <div class="col-12"><label class="form-label">Pelanggan</label><select name="contact_id" class="form-select" required>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></div>
        <div class="col-12"><label class="form-label">Produk / varian</label><select name="product_variant_id" class="form-select" required>@foreach($variants as $variant)<option value="{{ $variant->id }}">{{ $variant->sku }} · {{ $variant->product?->name }}</option>@endforeach</select></div>
        <div class="col-4"><label class="form-label">Jumlah</label><input name="quantity" type="number" min=".001" step=".001" class="form-control" required></div><div class="col-4"><label class="form-label">Harga</label><input name="unit_price" type="number" min="0" step=".01" class="form-control" required></div><div class="col-4"><label class="form-label">Diskon baris</label><input name="line_discount" type="number" min="0" step=".01" value="0" class="form-control"></div>
        <div class="col-6"><label class="form-label">Tanggal</label><input name="quotation_date" type="date" value="{{ today()->toDateString() }}" class="form-control" required></div><div class="col-6"><label class="form-label">Berlaku hingga</label><input name="valid_until" type="date" class="form-control"></div>
        <div class="col-6"><label class="form-label">Diskon dokumen</label><input name="discount" type="number" min="0" step=".01" value="0" class="form-control"></div><div class="col-6"><label class="form-label">Pajak</label><input name="tax" type="number" min="0" step=".01" value="0" class="form-control"></div>
        <div class="col-12"><label class="form-label">Catatan</label><textarea name="notes" rows="2" class="form-control"></textarea></div><div class="col-12"><button class="btn btn-primary w-100">Simpan draft</button></div>
    </form></div></div>
    <div class="col-12 col-xl-8"><div class="card"><div class="card-header"><h2 class="card-title">Quotation terbaru</h2></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Nomor</th><th>Pelanggan</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($quotations as $quotation)<tr><td><a target="_blank" href="{{ route('sales-documents.quotations.print', $quotation) }}">{{ $quotation->quotation_no }}</a><div class="small text-secondary">{{ $quotation->quotation_date->format('d M Y') }}</div></td><td>{{ $quotation->contact?->name }}</td><td>Rp {{ number_format((float) $quotation->total, 0, ',', '.') }}</td><td><span class="badge">{{ $quotation->status }}</span></td><td>@if($quotation->status === 'draft')<form method="POST" action="{{ route('sales-documents.quotations.transition', $quotation) }}" class="d-inline">@csrf<input type="hidden" name="status" value="sent"><button class="btn btn-sm btn-primary">Kirim</button></form>@elseif($quotation->status === 'sent')<form method="POST" action="{{ route('sales-documents.quotations.transition', $quotation) }}" class="d-inline">@csrf<input type="hidden" name="status" value="accepted"><button class="btn btn-sm btn-success">Terima</button></form><form method="POST" action="{{ route('sales-documents.quotations.transition', $quotation) }}" class="d-inline">@csrf<input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-outline-danger">Tolak</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Belum ada quotation.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
