@extends('layouts.tabler')
@section('title', 'Bundle & Combo')
@section('header', 'Bundle & Combo')
@section('content')
@if(session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="alert alert-info">Bundle tidak menyimpan stok sendiri. Penjualan, retur, dan void memutasi stok setiap komponen secara atomik.</div>
<div class="vstack gap-4">@forelse($bundles as $bundle)<section class="card"><div class="card-header"><div><h2 class="card-title mb-0">{{ $bundle->name }}</h2><p class="text-secondary mb-0">{{ $bundle->sku ?: 'Tanpa SKU' }}</p></div></div><form class="card-body" method="POST" action="{{ route('bundles.sync',$bundle) }}">@csrf<div class="bundle-items row g-3" data-items>
@forelse($bundle->bundleItems as $index=>$item)<div class="col-12 item-row"><div class="row g-2 align-items-end"><div class="col-12 col-md-7"><label class="form-label">Komponen</label><select class="form-select" name="items[{{ $index }}][component_variant_id]" required>@foreach($variants->where('product_id','!=',$bundle->id) as $variant)<option value="{{ $variant->id }}" @selected($item->component_variant_id===$variant->id)>{{ $variant->sku }} · {{ $variant->product?->name }}</option>@endforeach</select></div><div class="col-8 col-md-3"><label class="form-label">Qty / bundle</label><input class="form-control" type="number" min=".001" step=".001" name="items[{{ $index }}][quantity]" value="{{ $item->quantity }}" required></div><div class="col-4 col-md-2"><button class="btn btn-outline-danger w-100 remove-item" type="button">Hapus</button></div></div></div>@empty<div class="col-12 item-row"><div class="row g-2 align-items-end"><div class="col-12 col-md-7"><label class="form-label">Komponen</label><select class="form-select" name="items[0][component_variant_id]" required>@foreach($variants->where('product_id','!=',$bundle->id) as $variant)<option value="{{ $variant->id }}">{{ $variant->sku }} · {{ $variant->product?->name }}</option>@endforeach</select></div><div class="col-8 col-md-3"><label class="form-label">Qty / bundle</label><input class="form-control" type="number" min=".001" step=".001" name="items[0][quantity]" value="1" required></div><div class="col-4 col-md-2"><button class="btn btn-outline-danger w-100 remove-item" type="button">Hapus</button></div></div></div>@endforelse</div><div class="d-flex gap-2 mt-3 flex-wrap"><button class="btn btn-outline-secondary add-item" type="button">Tambah komponen</button><button class="btn btn-primary">Simpan komponen</button></div></form></section>@empty<div class="card"><div class="card-body text-center text-secondary py-5">Belum ada produk bertipe Bundle / Combo. Buat dari Master Produk, lalu atur komponennya di sini.</div></div>@endforelse</div>
<template id="bundle-row"><div class="col-12 item-row"><div class="row g-2 align-items-end"><div class="col-12 col-md-7"><label class="form-label">Komponen</label><select class="form-select" data-name="component_variant_id" required>@foreach($variants as $variant)<option value="{{ $variant->id }}">{{ $variant->sku }} · {{ $variant->product?->name }}</option>@endforeach</select></div><div class="col-8 col-md-3"><label class="form-label">Qty / bundle</label><input class="form-control" data-name="quantity" type="number" min=".001" step=".001" value="1" required></div><div class="col-4 col-md-2"><button class="btn btn-outline-danger w-100 remove-item" type="button">Hapus</button></div></div></div></template>
@push('scripts')<script>document.querySelectorAll('[data-items]').forEach(box=>{let next=box.querySelectorAll('.item-row').length;box.closest('form').querySelector('.add-item').addEventListener('click',()=>{const fragment=document.getElementById('bundle-row').content.cloneNode(true);fragment.querySelectorAll('[data-name]').forEach(el=>el.name=`items[${next}][${el.dataset.name}]`);box.append(fragment);next++;});box.addEventListener('click',event=>{if(event.target.closest('.remove-item')&&box.querySelectorAll('.item-row').length>1)event.target.closest('.item-row').remove();});});</script>@endpush
@endsection
