@extends('layouts.tabler')
@section('title', 'Jurnal Umum')
@section('header', 'Akuntansi · Jurnal Umum')
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="row row-cards">
<div class="col-12 col-xl-5"><div class="card"><div class="card-header"><h3 class="card-title">Jurnal baru (draft, harus seimbang)</h3></div><div class="card-body"><form method="POST" action="{{ route('accounting.journals.store') }}" id="journal-form">@csrf
<div class="row g-2 mb-2"><div class="col-6"><label class="form-label">Tanggal</label><input name="entry_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-6"><label class="form-label">Keterangan</label><input name="description" class="form-control" maxlength="255"></div></div>
<div id="journal-lines">
@for($i=0;$i<2;$i++)<div class="row g-1 mb-1 journal-line"><div class="col-4"><select name="lines[{{ $i }}][account_code]" class="form-select" required><option value="">Pilih akun</option>@foreach($accounts as $a)<option value="{{ $a->code }}">{{ $a->code }} · {{ $a->name }}</option>@endforeach</select></div><div class="col-3"><select name="lines[{{ $i }}][variant_id]" class="form-select"><option value="">Tanpa varian</option>@foreach($variants as $v)<option value="{{ $v->id }}">{{ $v->sku }} · {{ $v->product?->name }}</option>@endforeach</select></div><div class="col-2"><input name="lines[{{ $i }}][debit]" type="number" min="0" step="0.01" value="0" class="form-control" placeholder="Debit"></div><div class="col-2"><input name="lines[{{ $i }}][credit]" type="number" min="0" step="0.01" value="0" class="form-control" placeholder="Kredit"></div><div class="col-1"><button type="button" class="btn btn-outline-danger remove-line" aria-label="Hapus baris">×</button></div></div>@endfor
</div>
<button type="button" id="add-line" class="btn btn-sm btn-outline-primary mb-2">+ Tambah baris</button>
<button class="btn btn-primary w-100" type="submit">Simpan draft</button></form></div></div></div>
<div class="col-12 col-xl-7"><div class="card"><div class="card-header"><h3 class="card-title">Entri jurnal (100 terbaru)</h3></div><div class="table-responsive"><table class="table card-table table-vcenter"><thead><tr><th>No</th><th>Tanggal</th><th>Baris</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($entries as $e)<tr><td><strong>{{ $e->entry_no }}</strong><div class="small text-secondary">{{ $e->description }}</div></td><td>{{ $e->entry_date->toDateString() }}</td><td>@foreach($e->lines as $l)<div class="small">{{ $l->account?->code }} · D {{ number_format($l->debit,2,',','.') }} / K {{ number_format($l->credit,2,',','.') }}@if($l->variant) <span class="text-muted">· {{ $l->variant->sku }}</span>@endif</div>@endforeach</td><td><span class="badge">{{ $e->status }}</span></td><td class="text-nowrap">
@if($e->status==='draft')<form method="POST" action="{{ route('accounting.journals.post',$e) }}" class="d-inline">@csrf<button class="btn btn-sm btn-success">Posting</button></form>@endif
@if($e->status==='posted')<form method="POST" action="{{ route('accounting.journals.void',$e) }}" class="d-inline">@csrf<input name="reason" class="form-control form-control-sm mb-1" placeholder="Alasan (opsional)" maxlength="255"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Batalkan via jurnal reversal?')">Void</button></form>@endif
</td></tr>
@empty<tr><td colspan="5" class="text-center text-secondary py-4">Belum ada jurnal.</td></tr>@endforelse
</tbody></table></div></div></div>
</div>
@push('scripts')<script>
(()=>{const box=document.getElementById('journal-lines');let i=box.querySelectorAll('.journal-line').length;const variantOpts=box.querySelector('select[name="lines[0][variant_id]"]')?.innerHTML??'';document.getElementById('add-line').addEventListener('click',()=>{const row=document.createElement('div');row.className='row g-1 mb-1 journal-line';const acctOpts=box.querySelector('select[name="lines[0][account_code]"]')?.innerHTML??'';row.innerHTML=`<div class="col-4"><select name="lines[${i}][account_code]" class="form-select" required>${acctOpts}</select></div><div class="col-3"><select name="lines[${i}][variant_id]" class="form-select">${variantOpts}</select></div><div class="col-2"><input name="lines[${i}][debit]" type="number" min="0" step="0.01" value="0" class="form-control" placeholder="Debit"></div><div class="col-2"><input name="lines[${i}][credit]" type="number" min="0" step="0.01" value="0" class="form-control" placeholder="Kredit"></div><div class="col-1"><button type="button" class="btn btn-outline-danger remove-line" aria-label="Hapus baris">×</button></div>`;box.appendChild(row);i++;});box.addEventListener('click',e=>{if(e.target.closest('.remove-line')&&box.querySelectorAll('.journal-line').length>2)e.target.closest('.journal-line').remove();});})();
</script>@endpush
@endsection